### ISSUE TITLE
Update Documentation for 3.0.0

### ISSUE THREAD

**Issue by DaniRey** [unic/ScalaWebTest#79]
Following parts of the documentation require an update

- [x] JSON module #67 
- [x] Getting started and Download (update the version numbers)
- [x] new chapter describing how to use other browsers #74 
- [x] search for references regarding Scala 2.10
- [x] write the release notes, including migration description
- [x] document which env variables or -D parameters are available
- [x] document how configuration changed in general #12 
- [x] document how and when we can access response codes and response headers #21 
- [x] improve visualization of gauges

**Comment by DaniRey** [comment]
With https://github.com/unic/ScalaWebTest/commit/146e1dc7fec3f42176b197ce94c4a0dc132b24ae the most important parts are covered.
